// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0A5xzuVd--093eMC2PSkOrU_nrEc0H8w',
    appId: '1:45777911778:android:e28608a886df1a405643bb',
    messagingSenderId: '45777911778',
    projectId: 'aqi-new-422c7',
    databaseURL: 'https://aqi-new-422c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqi-new-422c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwXM-ZZPlUp8_6likaW6qsL1cYzRvuzc',
    appId: '1:45777911778:ios:85718595dcaaebf25643bb',
    messagingSenderId: '45777911778',
    projectId: 'aqi-new-422c7',
    databaseURL: 'https://aqi-new-422c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqi-new-422c7.firebasestorage.app',
    iosBundleId: 'com.example.aqi',
  );
}
